version: '3'

services:
      app:
            build: 
                context: .
            ports: 
                  - '8080:8080'
            environment: 
                  - HOME_PATH=/tmp/sales-importer/
            volumes: 
                  - ./files/:/tmp/sales-importer/
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.1/16                  