server:
    port: ${PORT:8080}

filesProcessor:
    importUri: file://${filesProcessor.directoryToImport}?scheduler=spring&scheduler.cron=${filesProcessor.importCron}&delay=1000&recursive=true&move=${filesProcessor.directoryProcessed}&moveFailed=${filesProcessor.directoryErrors}
    homePath: /home/fabio/Documents/sales-importer/
    directoryToImport: ${filesProcessor.homePath}in
    directoryToExport: ${filesProcessor.homePath}out
    directoryErrors: ${filesProcessor.homePath}errors
    directoryProcessed: ${filesProcessor.homePath}processed
    importCron: 0/5+*+*+?+*+*
    exportUri: file://${filesProcessor.directoryToExport}?fileExist=Override
    exportErrorsUri: file://${filesProcessor.directoryErrors}?fileExist=Override   
    
logging:
    level:
        org.apache.camel.component.file: INFO
        com.github.fabiosoaza.salesimporter: DEBUG